services:
  db:
    image: postgres
    restart: always
    shm_size: 512mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks: 
      - prisma-network 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"] 
      interval: 5s 
      timeout: 2s 
      retries: 20 
    volumes: 
      - pgdata:/var/lib/postgresql
    command: postgres -c listen_addresses='*'
    logging: 
      options: 
        max-size: "10m"
        max-file: "3"
networks: 
  prisma-network: 
volumes:
  pgdata: